version: '3'
services:
  app:
    build: .
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357
      - 9222:9222
    volumes:
      - .:/app
      - /app/.config
      - /app/dist
      - /app/electron-out
      - /app/node_modules
      - /app/tmp
    env_file: .env
